feat : add product listing page
Kavita539/KayyShoppe pull request #2
Opened 2022-02-16 17:48 UTC by Kavita539

Added Product Listing Page
1. Has Filters sidebar
2. Main Product Container showing the items in card
3. Navbar with searchbar

2022-02-16 18:16 UTC, ArjunGTX approved these changes

2022-02-16 18:16 UTC, ArjunGTX commented on pages/product-listing-page/product-listing.css
> +    display: none;
Disabling scrollbar will create a bad user experience. Try to reduce the width instead of hiding it.

2022-02-16 18:36 UTC, Kavita539 commented on pages/product-listing-page/product-listing.css
> +    display: none;
ok will do!

2022-02-17 04:45 UTC, prathmeshjagtap requested changes
i just could not figure out what are you you dividing  area with girds 
maybe that can be optimized
Everything  else looks good

2022-02-17 04:45 UTC, prathmeshjagtap commented on pages/product-listing-page/product-listing.css
> +        "footer footer footer footer footer footer";
why do you need to divide columns in this much  I think  
        "nav nav"
        "filters main-products "
        "footer footer ";

would just work 


and for smaller screen  
         "nav "
        "main-products "
        "footer";

2022-02-17 14:02 UTC, Kavita539 commented on pages/product-listing-page/product-listing.css
> +        "footer footer footer footer footer footer";
ok will do!

2022-02-17 14:03 UTC, prathmeshjagtap approved these changes

2022-02-17 14:12 UTC, merged